"""
Reset the telluric pipeline — remove all generated byproducts.

Deletes every file and directory that is produced by the pipeline so that the
next run starts completely fresh.  Input data (scidata_*, hotstars_*, sky_*,
templates_*, calib_*) and configuration files are NOT touched.

Byproducts removed
------------------
Directories (deleted entirely):
  tellu_fit_{instrument}/         hot-star transmission fits + big_table.csv
  residuals_{instrument}/         per-order residual correction maps
  tellupatched_{instrument}/      telluric-corrected science spectra
  tmp_{instrument}/               precomputed absorption grid cache (.pkl)
  slinky_{instrument}_output/     slinky wavelength-solution output
  slinky_{instrument}_plots/      slinky diagnostic plots
  calib_{instrument}_patched/     patched wavelength solutions from slinky
  {paper_figures_dir}/            paper-quality figures

Files (deleted individually):
  params_fit_tellu_{instrument}.csv   fitted scaling parameters (compil_stats)
  main_absorber_{instrument}.fits     dominant-absorber map (compil_stats)
  calib_{instrument}/*_slinky.fits    per-HC-frame slinky FITS files

Usage
-----
    python reset.py                        # interactive confirmation
    python reset.py --force                # skip confirmation prompt
    python reset.py --dry-run              # list files without deleting
    python reset.py --instrument SPIROU    # override instrument from config
"""

import argparse
import glob
import os
import shutil
import sys
import yaml


# ---------------------------------------------------------------------------
# Helpers
# ---------------------------------------------------------------------------

SCRIPT_DIR = os.path.dirname(os.path.abspath(__file__))


def _load_config():
    cfg_path = os.path.join(SCRIPT_DIR, 'telluric_config.yaml')
    with open(cfg_path) as fh:
        return yaml.safe_load(fh)


def _get_project_path(config):
    """Return project_path for the current machine."""
    machines = config.get('machines', {})
    for _name, mcfg in machines.items():
        detect = mcfg.get('detect_path', '')
        if detect and os.path.exists(detect):
            return mcfg['project_path']
    # Fallback: directory containing this script
    return SCRIPT_DIR


def _collect_targets(project_path, instrument, paper_figures_dir):
    """Return (dirs, files) lists of byproduct paths to delete."""
    dirs = [
        os.path.join(project_path, f'tellu_fit_{instrument}'),
        os.path.join(project_path, f'residuals_{instrument}'),
        os.path.join(project_path, f'tellupatched_{instrument}'),
        os.path.join(project_path, f'tmp_{instrument}'),
        os.path.join(project_path, f'slinky_{instrument}_output'),
        os.path.join(project_path, f'slinky_{instrument}_plots'),
        os.path.join(project_path, f'calib_{instrument}_patched'),
        paper_figures_dir,
    ]

    files = [
        os.path.join(project_path, f'params_fit_tellu_{instrument}.csv'),
        os.path.join(project_path, f'main_absorber_{instrument}.fits'),
    ]

    # _slinky.fits files written next to input HC calibration files
    slinky_pattern = os.path.join(project_path, f'calib_{instrument}', '*_slinky.fits')
    files.extend(sorted(glob.glob(slinky_pattern)))

    return dirs, files


def _fmt_size(path):
    """Return a human-readable size string for a file or directory."""
    try:
        if os.path.isdir(path):
            total = sum(
                os.path.getsize(os.path.join(dp, f))
                for dp, _, fnames in os.walk(path)
                for f in fnames
            )
        else:
            total = os.path.getsize(path)
    except OSError:
        return '?'
    for unit in ('B', 'KB', 'MB', 'GB'):
        if total < 1024:
            return f'{total:.0f} {unit}'
        total /= 1024
    return f'{total:.1f} TB'


def _print_plan(dirs, files):
    """Print what will be deleted."""
    any_found = False
    print('\nDirectories to delete:')
    for d in dirs:
        if os.path.exists(d):
            print(f'  [DIR]  {d}  ({_fmt_size(d)})')
            any_found = True
        else:
            print(f'  [---]  {d}  (not found)')

    print('\nFiles to delete:')
    for f in files:
        if os.path.exists(f):
            print(f'  [FILE] {f}  ({_fmt_size(f)})')
            any_found = True
        else:
            print(f'  [---]  {f}  (not found)')
    print()
    return any_found


def _do_delete(dirs, files, dry_run):
    deleted_dirs = 0
    deleted_files = 0
    for d in dirs:
        if os.path.exists(d):
            if not dry_run:
                shutil.rmtree(d)
            print(f'  Removed dir : {d}')
            deleted_dirs += 1
    for f in files:
        if os.path.exists(f):
            if not dry_run:
                os.remove(f)
            print(f'  Removed file: {f}')
            deleted_files += 1
    return deleted_dirs, deleted_files


# ---------------------------------------------------------------------------
# Main
# ---------------------------------------------------------------------------

def main():
    parser = argparse.ArgumentParser(
        description='Remove all pipeline byproducts for a fresh re-reduction.',
        formatter_class=argparse.RawDescriptionHelpFormatter,
    )
    parser.add_argument('--instrument', default=None,
                        help='Override instrument (NIRPS or SPIROU)')
    parser.add_argument('--force', action='store_true',
                        help='Skip confirmation prompt')
    parser.add_argument('--dry-run', action='store_true',
                        help='List targets without deleting anything')
    args = parser.parse_args()

    config = _load_config()
    instrument = (args.instrument or config.get('instrument', 'NIRPS')).upper()
    project_path = _get_project_path(config)

    paper_cfg = config.get('paper_figures', {})
    paper_figures_dir = os.path.join(
        project_path, paper_cfg.get('output_dir', 'paper_figures')
    )

    print(f'Instrument   : {instrument}')
    print(f'Project path : {project_path}')
    if args.dry_run:
        print('Mode         : DRY RUN (nothing will be deleted)')

    dirs, files = _collect_targets(project_path, instrument, paper_figures_dir)
    any_found = _print_plan(dirs, files)

    if not any_found:
        print('Nothing to remove — workspace is already clean.')
        return

    if args.dry_run:
        print('Dry-run complete. No files were deleted.')
        return

    if not args.force:
        try:
            answer = input('Proceed with deletion? [y/N] ').strip().lower()
        except (EOFError, KeyboardInterrupt):
            print('\nAborted.')
            sys.exit(1)
        if answer not in ('y', 'yes'):
            print('Aborted.')
            sys.exit(0)

    print('\nDeleting...')
    n_dirs, n_files = _do_delete(dirs, files, dry_run=False)
    print(f'\nDone — removed {n_dirs} director{"y" if n_dirs == 1 else "ies"} '
          f'and {n_files} file{"" if n_files == 1 else "s"}.')


if __name__ == '__main__':
    main()
